; IND1R kolxoz board
[env:meshtastic-ind1r-diy]
extends = esp32_base
board = esp32dev
board_level = extra
build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -D EBYTE_E22
  -D EBYTE_E22_900M30S
  -D HAS_ETHERNET
  -I variants/esp32/diy-ind1r
build_src_filter = 
  ${arduino_base.build_src_filter} -<platform/nrf52/> -<platform/stm32wl> -<platform/rp2xx0> -<mesh/raspihttp>
lib_deps =
  ${esp32_base.lib_deps}
  https://github.com/RAKWireless/RAK13800-W5100S/archive/1.0.2.zip
 